### ISSUE TITLE
Function call never yields result

### ISSUE THREAD

**Issue by berwyn** [timonson/gentle_rpc#6]
I have an Elgato WaveLink microphone, and the user-space software for that exposes a JSON-RPC interface to control the microphone. Using the following code, I can connect and attempt to issue a command against the software. The handler I directly register on the socket will log the message coming back just fine, but the `await`ed call never resolves. Any idea what could be causing this?

```
❯ deno --version
deno 1.8.1 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
```

```ts
import { createRemote } from './deps.ts';

console.log('Opening connection...');

const socket = new WebSocket('ws://127.0.0.1:1824');
socket.addEventListener('open', () => console.log('connection open'));
socket.addEventListener('message', message => console.debug(message)); // This will successfully log out the response
socket.addEventListener('error', error => console.error(error));
socket.addEventListener('close', () => console.log('connection closed'));

const remote = await createRemote(socket);
const appInfo = await remote.getApplicationInfo(); // This never resolves

console.log('Got app info:')
console.debug(appInfo);
```

**Comment by timonson** [comment]
The handlers you registered directly are - under working conditions - unnecessary but I am sure you already knew this. You are using the right syntax and it should actually work. Did you try the [ws example](https://github.com/timonson/gentle_rpc/tree/master/examples/ws_example) already? I only tested gentle_rpc on Linux yet but it should work on Windows, too. Please let me know if the examples don't work on your machine neither (with the exception of the `BadResource` error which will be [fixed in the next deno version](https://github.com/denoland/deno/issues/9879)).

Otherwise, is there another way to replicate this behavior without the microphone?

Thanks!

EDIT:

Does the server respond with a valid [RPC response object with an id](https://www.jsonrpc.org/specification#response_object)? You should be able to check this with your `message` handler. It is important that the response has an id in this case, please check this.

**Comment by berwyn** [comment]
Oh, good call on the response, I just checked the payload that returns and it seems to have `id: 0` instead of the one that went on the request! The payload looks otherwise well-formed, so it seems like Elgato isn't correctly matching the id of the request with the response. Well, guess that's something to file with them. Thanks for the help!

That said, I did attempt to run the examples and they _do not_ seem to work on Windows (at least on my machine) but that's something I can look into and PR separately :)
